services:
  - type: web
    name: simtech-next
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx next start -p 10000
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: IRON_SESSION_PASSWORD
        sync: false
      - key: NEXT_PUBLIC_BASE_URL 
        sync: false
      - key: PHONEPE_CLIENT_ID
        sync: false
      - key: PHONEPE_CLIENT_SECRET
        sync: false
      - key: PHONEPE_CLIENT_VERSION
        sync: false
      - key: PHONEPE_ENV
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
      - key: NEXT_PUBLIC_VAPID_PUBLIC_KEY
        sync: false
    autoDeploy: true
